# Generated by Django 5.1.7 on 2025-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=100)),
                ('numeroTelefono', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
