# Generated by Django 5.1.6 on 2025-03-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0004_rename_edad1_cliente_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='edad',
            new_name='edadc',
        ),
    ]
